---
apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion-comfy-ui
  labels:
    app: stable-diffusion-comfy-ui
  namespace: brick-bench
spec:
  selector:
    app: stable-diffusion-comfy-ui
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkpoints-pv
  namespace: brick-bench
spec:
  capacity:
    storage: 17Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/cc/models/checkpoints
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clip-pv
  namespace: brick-bench
spec:
  capacity:
    storage: 11.2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/cc/models/clip/text_encoders
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkpoints-pvc
  namespace: brick-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 17Gi
  volumeName: checkpoints-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clip-pvc
  namespace: brick-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11.2Gi
  volumeName: clip-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-comfy-ui
  namespace: brick-bench
  labels:
    app: stable-diffusion-comfy-ui
spec:
  selector:
    matchLabels:
      app: stable-diffusion-comfy-ui
  template:
    metadata:
      labels:
        app: stable-diffusion-comfy-ui
    spec:
      runtimeClassName: nvidia
      containers:
        - name: image-gen
          image: devlew/comfy-ui:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /stable-diffusion/models/checkpoints
              name: checkpoints
            - mountPath: /stable-diffusion/models/clip
              name: clip

      volumes:
        - name: checkpoints
          persistentVolumeClaim:
            claimName: checkpoints-pvc
        - name: clip
          persistentVolumeClaim:
            claimName: clip-pvc
