---
apiVersion: v1
kind: Service
metadata:
  name: wan2.1-comfy-ui
  labels:
    app: wan2.1-comfy-ui
  namespace: brick-bench
spec:
  selector:
    app: wan2.1-comfy-ui
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wan2.1-vae-pv
  namespace: brick-bench
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/cc/models/vae
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wan2.1-clip-pv
  namespace: brick-bench
spec:
  capacity:
    storage: 6.8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/cc/models/clip/text_encoders
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wan2.1-diffusion-models-pv
  namespace: brick-bench
spec:
  capacity:
    storage: 6.8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/cc/models/diffusion_models/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wan2.1-vae-pvc
  namespace: brick-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6.8Gi
  volumeName: wan2.1-vae-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wan2.1-clip-pvc
  namespace: brick-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11.2Gi
  volumeName: wan2.1-clip-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wan2.1-diffusion-model-pvc
  namespace: brick-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11.2Gi
  volumeName: wan2.1-diffusion-model-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wan2.1-comfy-ui
  namespace: brick-bench
  labels:
    app: wan2.1-comfy-ui
spec:
  selector:
    matchLabels:
      app: wan2.1-comfy-ui
  template:
    metadata:
      labels:
        app: wan2.1-comfy-ui
    spec:
      containers:
        - name: image-gen
          image: devlew/comfy-ui:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /stable-diffusion/models/clip
              name: clip
            - mountPath: /stable-diffusion/models/diffusion_models
              name: diffusion_models
            - mountPath: /stable-diffusion/models/vae
              name: vae
      volumes:
        - name: vae
          persistentVolumeClaim:
            claimName: wan2.1-vae-pvc
        - name: clip
          persistentVolumeClaim:
            claimName: wan2.1-clip-pvc
