---
apiVersion: v1
kind: Service
metadata:
  name: wan-comfy-ui
  labels:
    app: wan-comfy-ui
  namespace: brick-bench
spec:
  selector:
    app: wan-comfy-ui
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wan-vae-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/cc/models/vae
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wan-clip-pv
spec:
  capacity:
    storage: 6.8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/cc/models/clip/text_encoders
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wan-clip-vision-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/cc/models/clip_vision
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wan-diffusion-models-pv
spec:
  capacity:
    storage: 36Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/cc/models/diffusion_models/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wan-clip-pvc
  namespace: brick-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6.8Gi
  volumeName: wan-clip-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wan-vae-pvc
  namespace: brick-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  volumeName: wan-vae-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wan-diffusion-models-pvc
  namespace: brick-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 36Gi
  volumeName: wan-diffusion-models-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wan-clip-vision-pvc
  namespace: brick-bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: wan-clip-vision-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wan-comfy-ui
  namespace: brick-bench
  labels:
    app: wan-comfy-ui
spec:
  selector:
    matchLabels:
      app: wan-comfy-ui
  template:
    metadata:
      labels:
        app: wan-comfy-ui
    spec:
      runtimeClassName: nvidia
      containers:
        - name: video-gen
          image: devlew/comfy-ui:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /stable-diffusion/models/clip
              name: clip
            - mountPath: /stable-diffusion/models/clip_vision
              name: clip-vision
            - mountPath: /stable-diffusion/models/diffusion_models
              name: diffusion-models
            - mountPath: /stable-diffusion/models/vae
              name: vae
      volumes:
        - name: clip
          persistentVolumeClaim:
            claimName: wan-clip-pvc
        - name: clip-vision
          persistentVolumeClaim:
            claimName: wan-clip-vision-pvc
        - name: diffusion-models
          persistentVolumeClaim:
            claimName: wan-diffusion-models-pvc
        - name: vae
          persistentVolumeClaim:
            claimName: wan-vae-pvc
