---
- name: Setup nvidia-container-toolkit-base
  hosts: worker
  tasks:
    - name: Install nvidia-container-toolkit
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        state: present

    # The nvidia runtime class is required for the GPU operator, so we configure that.
    # All GPU workload pods will specify the nvidia runtime class in their manifests.
    # All other pods should be using containerd by default. Tried to get CDI working
    # but could not succeed
    - name: Configure nvidia-container-runtime
      ansible.builtin.command: nvidia-ctk runtime configure --runtime=containerd

    - name: Restart containerd
      ansible.builtin.systemd_service:
        name: containerd
        state: restarted
  become: true
  tags:
    - toolkit
    - gpu

- name: Setup gpu-operator
  hosts: controller
  tasks:
    - name: Add helm repository
      ansible.builtin.deb822_repository:
        name: helm
        signed_by: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
        suites: any
        components: main
        uris: https://packages.buildkite.com/helm-linux/helm-debian/any/
        state: present
        enabled: true
      become: true

    - name: Install helm
      ansible.builtin.apt:
        name: helm
        state: present
        update_cache: true
      become: true

    - name: Add nvidia helm repository
      kubernetes.core.helm_repository:
        name: nvidia
        repo_url: https://helm.ngc.nvidia.com/nvidia

    - name: Install gpu-operator
      kubernetes.core.helm:
        name: gpu-operator
        chart_ref: nvidia/gpu-operator
        release_namespace: gpu-operator
        create_namespace: true
        update_repo_cache: true
        wait: true
        values:
          driver:
            enabled: false
          toolkit:
            enabled: false
  tags: gpu

- name: Install Stable Diffusion and WAN2.1 prerequisites
  hosts: worker
  vars:
    huggingface_cli_executable: "{{ home }}/.virtualenvs/hf/bin/hf"
  tasks:
    # All subsequent invocations of huggingface-cli will use this virtualenv.
    - name: Install huggingface-cli
      ansible.builtin.pip:
        name: "huggingface_hub"
        state: present
        virtualenv: "{{ home }}/.virtualenvs/hf"
        virtualenv_command: python3 -m venv
      when: token is defined

    - name: Create directories
      ansible.builtin.file:
        path: "{{ home }}/models/{{ item }}"
        state: directory
        owner: cc
        mode: 0755
      loop:
        - checkpoints
        - clip
        - diffusion_models
        - vae
      when: token is defined

    - name: Login with token
      ansible.builtin.command: "{{ huggingface_cli_executable }} auth login --token {{ token }}"
      when: token is defined

    - name: Download Stable Diffusion 3.5 model
      ansible.builtin.command: >
        {{ huggingface_cli_executable }} download stabilityai/stable-diffusion-3.5-large sd3.5_large.safetensors
        --local-dir {{ home }}/models/checkpoints
      when: token is defined

    - name: Download Wan2.1 text-to-video and image-to-video models
      ansible.builtin.command: >
        {{ huggingface_cli_executable }} download Comfy-Org/Wan_2.1_ComfyUI_repackaged
        split_files/diffusion_models/{{ item }}
        --local-dir {{ home }}/models/diffusion_models
      loop:
        - wan2.1_i2v_480p_14B_fp16.safetensors
        - wan2.1_t2v_1.3B_fp16.safetensors
      when: token is defined

    - name: Download Wan2.1 clip vision
      ansible.builtin.command: >
        {{ huggingface_cli_executable }} download Comfy-Org/Wan_2.1_ComfyUI_repackaged
        split_files/clip_vision/clip_vision_h.safetensors
        --local-dir {{ home }}/models/clip_vision
      when: token is defined

    - name: Download Wan2.1 VAE
      ansible.builtin.command: >
        {{ huggingface_cli_executable }} download Comfy-Org/Wan_2.1_ComfyUI_repackaged
        split_files/vae/wan_2.1_vae.safetensors
        --local-dir {{ home }}/models/vae

    - name: Download Stable Diffusion text encoders
      ansible.builtin.command: >
        {{ huggingface_cli_executable }} download stabilityai/stable-diffusion-3.5-large text_encoders/{{ item }}
        --local-dir {{ home }}/models/clip
      loop:
        - clip_g.safetensors
        - clip_l.safetensors
        - t5xxl_fp16.safetensors
      when: token is defined

    - name: Download Wan2.1 text encoder
      ansible.builtin.command: >
        {{ huggingface_cli_executable }} download Comfy-Org/Wan_2.1_ComfyUI_repackaged
        split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors
        --local-dir {{ home }}/models/clip/text_encoders
      when: token is defined

    - name: Move Wan2.1 text encoder to correct location
      ansible.builtin.command: >
        mv {{ home }}/models/clip/text_encoders/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors
        {{ home }}/models/clip/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors
      when: token is defined

    - name: Remove Wan2.1 text encoder leftover directory
      ansible.builtin.file:
        path: "{{ home }}/models/clip/text_encoders/split_files"
        state: absent
      when: token is defined
  tags: prereq

- name: Deploy benchmark
  hosts: controller
  vars:
    kubernetes_venv_interpreter: "{{ home }}/.virtualenvs/kubernetes/bin/python3"
  tasks:
    - name: Create brick-bench namespace
      kubernetes.core.k8s:
        name: brick-bench
        kind: Namespace
        state: present
      vars:
        ansible_python_interpreter: "{{ kubernetes_venv_interpreter }}"

    - name: Apply image gen manifests
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'kubernetes-manifests/{{ image_gen_manifest }}') | from_yaml_all }}"
        namespace: brick-bench
        state: present
        force: true
      when: image_gen_manifest is defined
      vars:
        ansible_python_interpreter: "{{ kubernetes_venv_interpreter }}"

    - name: Apply video gen manifests
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'kubernetes-manifests/{{ video_gen_manifest }}') | from_yaml_all }}"
        namespace: brick-bench
        state: present
        force: true
      when: video_gen_manifest is defined
      vars:
        ansible_python_interpreter: "{{ kubernetes_venv_interpreter }}"
  tags: deploy
