# Import public network to assign floating ips to the instances on the private network
data "openstack_networking_network_v2" "public" {
  name = "public"
}

resource "openstack_networking_network_v2" "network" {
  name           = "${var.name_prefix}_network"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "subnet" {
  name            = "${var.name_prefix}_subnet"
  cidr            = "192.168.0.0/16"
  dns_nameservers = ["8.8.8.8", "8.8.4.4"]
  network_id      = openstack_networking_network_v2.network.id
}

resource "openstack_networking_router_v2" "router" {
  name                = "${var.name_prefix}_router"
  admin_state_up      = "true"
  external_network_id = data.openstack_networking_network_v2.public.id
}

resource "openstack_networking_router_interface_v2" "router_interface" {
  subnet_id = openstack_networking_subnet_v2.subnet.id
  router_id = openstack_networking_router_v2.router.id
}

resource "openstack_networking_floatingip_v2" "floating_ips" {
  count = 2
  pool  = "public"
}

resource "openstack_compute_floatingip_associate_v2" "floatingip_associate_cpu" {
  count = var.use_gpu ? 1 : 2

  floating_ip = openstack_networking_floatingip_v2.floating_ips[count.index].address
  instance_id = openstack_compute_instance_v2.cpu_instance[count.index].id
}

resource "openstack_compute_floatingip_associate_v2" "floatingip_associate_gpu" {
  count = var.use_gpu ? 1 : 0

  floating_ip = openstack_networking_floatingip_v2.floating_ips[1].address
  instance_id = openstack_compute_instance_v2.gpu_instance[count.index].id
}

resource "openstack_networking_secgroup_v2" "secgroup" {
  name = "${var.name_prefix}_secgroup"
}

resource "openstack_networking_secgroup_rule_v2" "ping_secgroup_rule" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "icmp"
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = openstack_networking_secgroup_v2.secgroup.id
}

# This range could probably be shrunk, but this is simpler
resource "openstack_networking_secgroup_rule_v2" "all_ports_rule" {
  direction         = "ingress"
  ethertype         = "IPv4"
  port_range_max    = "0"
  port_range_min    = "0"
  protocol          = "tcp"
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = openstack_networking_secgroup_v2.secgroup.id
}

resource "openstack_compute_keypair_v2" "keypair" {
  name = "${var.name_prefix}_keypair"
}

resource "openstack_compute_instance_v2" "cpu_instance" {
  count      = var.use_gpu ? 1 : 2
  depends_on = [openstack_networking_subnet_v2.subnet]

  name            = count.index == 0 ? "controller" : "worker"
  flavor_name     = "baremetal"
  image_name      = "CC-Ubuntu24.04"
  key_pair        = openstack_compute_keypair_v2.keypair.name
  security_groups = [openstack_networking_secgroup_v2.secgroup.name]

  network {
    name = openstack_networking_network_v2.network.name
  }

  scheduler_hints {
    additional_properties = {
      "reservation" = var.reservation_id_cpu
    }
  }
}

resource "openstack_compute_instance_v2" "gpu_instance" {
  count      = var.use_gpu ? 1 : 0
  depends_on = [openstack_networking_subnet_v2.subnet]

  name            = "worker"
  flavor_name     = "baremetal"
  image_name      = "CC-Ubuntu24.04-CUDA"
  key_pair        = openstack_compute_keypair_v2.keypair.name
  security_groups = [openstack_networking_secgroup_v2.secgroup.name]

  network {
    name = openstack_networking_network_v2.network.name
  }

  scheduler_hints {
    additional_properties = {
      "reservation" = var.reservation_id_gpu
    }
  }
}

resource "local_file" "ansible_hosts_file" {
  content = <<-EOF
    # This file was autogenerated by Terraform
    [controller]
    ${openstack_networking_floatingip_v2.floating_ips[0].address}

    [worker]
    ${openstack_networking_floatingip_v2.floating_ips[1].address}
  EOF

  filename = "../ansible/inventory/hosts"
}

resource "local_file" "ansible_group_vars_all_file" {
  content = <<-EOF
    # This file was autogenerated by Terraform
    ansible_user: cc
    ansible_ssh_private_key_file: ${var.path_to_key}/brick-bench-key
    home: /home/cc
  EOF

  filename = "../ansible/inventory/group_vars/all.yaml"
}

resource "local_sensitive_file" "private_key_file" {
  content         = openstack_compute_keypair_v2.keypair.private_key
  filename        = "${var.path_to_key}/brick-bench-key"
  file_permission = "0600"
}
